### ISSUE TITLE
windows 10 camera wont detect?

### ISSUE THREAD

**Issue by SicknUnDope** [kitohe/android-cam-to-pc#1]
launched tools-virtualcam also start virtual camera wont work for windows cam

**Comment by kitohe** [comment]
Hi. On newest version of OBS, it seems like virtual camera is already added by default, so you don't have to install any plugins. I checked on newest installation of OBS and it works correctly for me on Windows 10, and camera is detected on Discord (that's where I checked it). If it doesn't work for you please try to uninstall VirtualCam addon. I've updated a README with newest instructions. New option to start virtual camera is under `Controls` section:

![image](https://user-images.githubusercontent.com/11276441/123507506-2032a700-d66a-11eb-9ec8-683ff025508c.png)
